import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useLiveData } from '../hooks/useLiveData';
import './Dashboard.css';
import {
  Chart as ChartJS, LineElement, CategoryScale, LinearScale,
  PointElement, BarElement, ArcElement, Filler, Tooltip, Legend
} from 'chart.js';
import { Line, Bar, Doughnut } from 'react-chartjs-2';

ChartJS.register(LineElement, CategoryScale, LinearScale, PointElement,
  BarElement, ArcElement, Filler, Tooltip, Legend);

export default function Dashboard() {
  const { user, logout } = useAuth();
  const { latest, history, source, connected } = useLiveData();
  const [bills, setBills] = useState([]);
  const [currentBill, setCurrentBill] = useState(null);
  const { token } = useAuth();

  useEffect(() => {
    if (!token) return;
    fetch('/api/bills', { headers: { Authorization: `Bearer ${token}` } })
      .then(r => r.json()).then(d => setBills(d.bills || []));
    fetch('/api/bills/current', { headers: { Authorization: `Bearer ${token}` } })
      .then(r => r.json()).then(d => setCurrentBill(d.bill));
  }, [token]);

  const isLive = source === 'esp' || source === 'sim';

  function downloadBill(bill) {
    const content = `MSEDCL - SMART ENERGY METER BILL
${'='.repeat(50)}
Consumer: ${user.name}
Consumer No: ${user.consumerNo}
Meter No: ${user.meterNo}
Address: ${user.address}
${'='.repeat(50)}
Bill Month: ${bill.billMonth}
Units Consumed: ${bill.unitsConsumed} kWh
Bill Amount: Rs. ${bill.billAmount}
Due Date: ${bill.dueDate}
${'='.repeat(50)}
Energy Charge: Rs. ${bill.breakdown?.energyCharge?.toFixed(2)}
Fixed Charge: Rs. ${bill.breakdown?.fixedCharge?.toFixed(2)}
LPSC: Rs. ${bill.breakdown?.lpsc?.toFixed(2)}
Division Duty: Rs. ${bill.breakdown?.divisionDuty?.toFixed(2)}
${'='.repeat(50)}
Status: ${bill.isPaid ? 'PAID' : 'UNPAID'}
Generated by SmartEnergy Monitor`;
    const blob = new Blob([content], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `Bill_${bill.billMonth}_${user.consumerNo}.txt`;
    a.click();
  }

  async function startMock() {
    await fetch('/api/readings/mock-start', {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` }
    });
    alert('Mock started — data is now saving to MongoDB every 5 seconds');
  }

  async function stopMock() {
    await fetch('/api/readings/mock-stop', {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` }
    });
    alert('Mock stopped');
  }

  async function generateBill() {
    const month = new Date().toISOString().slice(0, 7);
    const res = await fetch('/api/bills/generate', {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ month })
    });
    const data = await res.json();
    if (data.bill) {
      setCurrentBill(data.bill);
      setBills(prev => [data.bill, ...prev.filter(b => b.billMonth !== data.bill.billMonth)]);
      alert(`Bill generated! Amount: ₹${data.bill.billAmount}`);
    } else {
      alert('Error: ' + (data.error || 'unknown'));
    }
  }

  const hours = Array.from({ length: history.length }, (_, i) => {
    const t = history[i]?.timestamp;
    return t ? new Date(t).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : `#${i+1}`;
  });

  const lineOpts = {
    responsive: true, maintainAspectRatio: false, animation: false,
    scales: {
      x: { grid: { display: false }, border: { display: false }, ticks: { maxTicksLimit: 6, font: { size: 10 } } },
      y: { grid: { color: '#F1F5F9' }, border: { display: false }, ticks: { font: { size: 10 } } }
    },
    plugins: { legend: { display: false }, tooltip: { mode: 'index', intersect: false } },
    elements: { point: { radius: 0 }, line: { tension: 0.4, borderWidth: 2 } }
  };

  return (
    <div className="dash">
      {/* TOPBAR */}
      <div className="topbar">
        <div className="brand">
          <span className="brand-icon">⚡</span>
          <div>
            <div className="brand-name">Smart Energy Meter</div>
            <div className="brand-sub">Energy Monitoring System</div>
          </div>
        </div>
        <div className="nav-right">
          <div className={`source-badge ${isLive ? 'live' : 'mock'}`}>
            <span className="dot" />
            {isLive ? `Live — ESP32` : 'Mock Data — No Device'}
          </div>
          <div className={`ws-badge ${connected ? 'ok' : 'off'}`}>
            WS {connected ? 'Connected' : 'Disconnected'}
          </div>
          <button className="logout-btn" onClick={logout}>Logout</button>
        </div>
      </div>

      <div className="page">
        {/* MOCK BANNER */}
        {!isLive && (
          <div className="mock-banner">
            <span>⚠</span>
            <span>
              <strong>No ESP32 connected.</strong> Showing simulated data.
              Once your ESP32 starts sending readings to <code>POST /api/readings</code>,
              this banner disappears and all values update to real data automatically.
            </span>
          </div>
        )}

        {/* CONSUMER STRIP */}
        <div className="consumer-card">
          <div className="cc-header">
            <div className="cc-col">
              <div className="cc-label">Consumer Name</div>
              <div className="cc-name">{user?.name}</div>
              <div className="cc-addr">{user?.address}</div>
            </div>
            <div className="cc-col center">
              <div className="cc-label">Consumer No.</div>
              <div className="cc-big">{user?.consumerNo}</div>
            </div>
            <div className="cc-col right">
              <div className="cc-label">Meter No.</div>
              <div className="cc-val-lg">{user?.meterNo}</div>
              <div className="cc-label" style={{marginTop:6}}>Due Amount</div>
              <div className="cc-val-lg red">{currentBill ? `₹ ${currentBill.billAmount}` : '—'}</div>
            </div>
          </div>
          <div className="cc-strip">
            <div className="cc-cell"><div className="cc-lbl">Tariff</div><div className="cc-v">{user?.tariff}</div></div>
            <div className="cc-cell"><div className="cc-lbl">Sanction Load</div><div className="cc-v green">{user?.sanctionLoad} kW</div></div>
            <div className="cc-cell"><div className="cc-lbl">Circle</div><div className="cc-v">{user?.circle || '—'}</div></div>
            <div className="cc-cell"><div className="cc-lbl">Phone</div><div className="cc-v">{user?.phone || '—'}</div></div>
            <div className="cc-cell"><div className="cc-lbl">Supply Date</div><div className="cc-v">{user?.supplyDate || '—'}</div></div>
            <div className="cc-cell"><div className="cc-lbl">Data Source</div><div className={`cc-v ${isLive?'green':'amber'}`}>{source.toUpperCase()}</div></div>
          </div>
        </div>

        {/* KPI CARDS */}
        <div className="kpi-grid">
          {[
            { label: 'Voltage', val: latest?.voltage ?? '—', unit: 'V', color: '#1A4FBD', status: latest ? (latest.voltage >= 220 && latest.voltage <= 240 ? 'ok' : 'warn') : '' },
            { label: 'Current', val: latest?.current ?? '—', unit: 'A', color: '#F59E0B', status: '' },
            { label: 'Active Power', val: latest?.power ?? '—', unit: 'W', color: '#166534', status: latest && user ? (latest.power/1000 < user.sanctionLoad ? 'ok' : 'warn') : '' },
            { label: 'Power Factor', val: latest?.powerFactor ?? '—', unit: '', color: '#5B21B6', status: latest?.powerFactor ? (latest.powerFactor >= 0.9 ? 'ok' : 'warn') : '' },
            { label: 'Frequency', val: latest?.frequency ?? '—', unit: 'Hz', color: '#0E7490', status: '' },
          ].map(k => (
            <div className="kpi" key={k.label}>
              <div className="kpi-bar" style={{ background: k.color }} />
              <div className="kpi-label">{k.label}</div>
              <div className="kpi-val">{k.val}<span className="kpi-unit">{k.unit}</span></div>
              {k.status && <div className={`kpi-status ${k.status}`}>{k.status === 'ok' ? '✓ Normal' : '⚠ Check'}</div>}
            </div>
          ))}
        </div>

        {/* WAVEFORM CHARTS */}
        <div className="sec-hd">Live Waveforms</div>
        <div className="row-3">
          {[
            { label: 'Voltage (V)', key: 'voltage', color: '#1A4FBD' },
            { label: 'Current (A)', key: 'current', color: '#F59E0B' },
            { label: 'Power (W)',   key: 'power',   color: '#166534' },
          ].map(ch => (
            <div className="card" key={ch.key}>
              <div className="card-title">{ch.label}</div>
              <div style={{ height: 110 }}>
                <Line
                  data={{
                    labels: hours,
                    datasets: [{
                      data: history.map(r => r[ch.key]),
                      borderColor: ch.color,
                      backgroundColor: ch.color + '18',
                      fill: true,
                    }]
                  }}
                  options={lineOpts}
                />
              </div>
            </div>
          ))}
        </div>

        {/* BILL SECTION */}
        <div className="sec-hd">
  Bills
  <div style={{display:'flex', gap:8}}>
    <button className="dl-btn" style={{background:'#166534'}} onClick={startMock}>
      ▶ Start Saving Mock Data
    </button>
    <button className="dl-btn" style={{background:'#991B1B'}} onClick={stopMock}>
      ■ Stop
    </button>
    <button className="dl-btn" onClick={generateBill}>
      Generate Bill
    </button>
    {currentBill && (
      <button className="dl-btn" onClick={() => downloadBill(currentBill)}>
        ⬇ Download Bill
      </button>
    )}
  </div>
</div>

        <div className="row-2b">
          {/* Bill history table */}
          <div className="card">
            <div className="card-title">Billing History</div>
            {bills.length === 0 ? (
              <div className="empty">No bills generated yet. Bills are created automatically at month end.</div>
            ) : (
              <table className="data-tbl">
                <thead>
                  <tr><th>Month</th><th>Units</th><th>Amount</th><th>Status</th><th></th></tr>
                </thead>
                <tbody>
                  {bills.map(b => (
                    <tr key={b._id}>
                      <td>{b.billMonth}</td>
                      <td className="mono">{b.unitsConsumed}</td>
                      <td className="mono">₹ {b.billAmount}</td>
                      <td><span className={`badge ${b.isPaid ? 'b-green' : 'b-amber'}`}>{b.isPaid ? 'Paid' : 'Due'}</span></td>
                      <td><button className="dl-sm" onClick={() => downloadBill(b)}>⬇</button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>

          {/* Current bill breakdown */}
          <div className="card dark-card">
            <div className="card-title" style={{ color: '#E2E8F0' }}>Current Bill Details</div>
            {!currentBill ? (
              <div className="empty" style={{ color: '#64748B' }}>Bill not generated yet for this month.</div>
            ) : (
              <>
                <div className="bdb-row"><span>Units Consumed</span><span>{currentBill.unitsConsumed} kWh</span></div>
                <div className="bdb-row"><span>Energy Charge</span><span>₹ {currentBill.breakdown?.energyCharge?.toFixed(2)}</span></div>
                <div className="bdb-row"><span>Fixed Charge</span><span>₹ {currentBill.breakdown?.fixedCharge?.toFixed(2)}</span></div>
                <div className="bdb-row"><span>LPSC</span><span>₹ {currentBill.breakdown?.lpsc?.toFixed(2)}</span></div>
                <div className="bdb-row"><span>Division Duty</span><span>₹ {currentBill.breakdown?.divisionDuty?.toFixed(2)}</span></div>
                <div className="bdb-row total"><span>Total Payable</span><span>₹ {currentBill.billAmount}</span></div>
                <div className="bdb-row"><span>Due Date</span><span className="red">{currentBill.dueDate}</span></div>
                <button className="dl-btn" style={{ marginTop: 14, width: '100%' }} onClick={() => downloadBill(currentBill)}>
                  ⬇ Download Bill PDF
                </button>
              </>
            )}
          </div>
        </div>

        {/* POWER FACTOR DOUGHNUT */}
        <div className="row-2">
          <div className="card">
            <div className="card-title">Monthly Consumption (kWh)</div>
            <div style={{ height: 160 }}>
              <Bar
                data={{
                  labels: bills.slice(-6).map(b => b.billMonth),
                  datasets: [{
                    data: bills.slice(-6).map(b => b.unitsConsumed),
                    backgroundColor: '#1A4FBD',
                    borderRadius: 4,
                  }]
                }}
                options={{
                  responsive: true, maintainAspectRatio: false,
                  plugins: { legend: { display: false } },
                  scales: {
                    x: { grid: { display: false }, border: { display: false } },
                    y: { grid: { color: '#F1F5F9' }, border: { display: false } }
                  }
                }}
              />
            </div>
          </div>
          <div className="card" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
            <div className="card-title" style={{ textAlign: 'center' }}>Power Factor</div>
            <div style={{ width: 140, height: 140, position: 'relative' }}>
              <Doughnut
                data={{
                  datasets: [{
                    data: [
                      Math.round((latest?.powerFactor ?? 0.94) * 100),
                      100 - Math.round((latest?.powerFactor ?? 0.94) * 100)
                    ],
                    backgroundColor: ['#1A4FBD', '#E8F0FD'],
                    borderWidth: 0,
                  }]
                }}
                options={{ cutout: '75%', plugins: { legend: { display: false }, tooltip: { enabled: false } } }}
              />
              <div className="pf-center">
                <div className="pf-val">{latest?.powerFactor ?? '0.94'}</div>
                <div className="pf-lbl">PF</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}